version: '3.8'
services:
  redis-server:
    container_name: redis-server
    hostname: redis-server
    image: 'redis:latest'
    restart: always
    ports:
      - '6300:6379'
    volumes:
      - ./data:/data
    command: /bin/sh -c "redis-server --requirepass root"
  
  redis-server-ui:
    container_name: redis-server-ui
    hostname: redis-server-ui
    image: 'rediscommander/redis-commander:latest'
    restart: always
    ports:
      - '9000:8081'
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PASSWORD=root
      - HTTP_USER=root
      - HTTP_PASSWORD=root
  
  postgres-server:
    container_name: postgres-server
    hostname: postgres-server
    image: 'postgres:latest'
    restart: always
    ports:
      - '5430:5432'
    volumes:
      - ./postgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  postgres-server-ui:
    container_name: postgres-server-ui
    hostname: postgres-server-ui
    image: 'dpage/pgadmin4'
    restart: always
    ports:
      - '9001:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root

  zookeeper-instance-0:
    container_name: zookeeper-instance-0
    hostname: zookeeeper-instance-0
    image: 'confluentinc/cp-zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  apache-kafka-broker-0:
    container_name: apache-kafka-broker-0
    hostname: apache-kafka-broker-0
    image: confluentinc/cp-kafka:latest
    ports:
     - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeeper-instance-0:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    depends_on:
     - zookeeper-instance-0
